name: Release UrlKnight Exe

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 📥 Checkout del código
      uses: actions/checkout@v5

    - name: 🐍 Configurar Python 3.13.2
      uses: actions/setup-python@v6
      with:
        python-version: '3.13.2'

    - name: 📦 Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🔨 Compilar a ejecutable (.exe)
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon "assets/UrlKnight.ico" --add-data "assets;assets" --splash "assets/Carga.png" --name "UrlKnight" src/main.py

    - name: 📂 Preparar Carpeta de Distribución
      shell: pwsh
      run: |
        # Creamos la carpeta que verá el usuario
        New-Item -Path "dist\UrlKnight" -ItemType Directory
        # Movemos el exe dentro
        Move-Item -Path "dist\UrlKnight.exe" -Destination "dist\UrlKnight\"
        
    - name: 🤐 Comprimir en ZIP
      shell: pwsh
      run: |
        Compress-Archive -Path "dist\UrlKnight" -DestinationPath "dist\UrlKnight_v${{ github.ref_name }}.zip"

    - name: 🚀 Crear Release en GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: dist/UrlKnight_v${{ github.ref_name }}.zip
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
